### ISSUE TITLE
Official Retinaface mnet25 models conversion

### ISSUE THREAD

**Issue by SthPhoenix** [zheshipinyinMc/arcface_retinaface_mxnet2onnx#4]
Hi! Great work converting RetinaFace mnet25 model!
I am trying to convert models from official InsightFace python package  model zoo (retinaface_mnet025_v1, retinaface_mnet025_v2) using your code. Conversion works fine, but inference output is totally different from MXNet model, making it incompatible with following post processing. 
Converted original @yangfly  model works as intended.

**Comment by zheshipinyinMc** [comment]
can you show me the link retinaface_mnet025_v1, retinaface_mnet025_v2

**Comment by SthPhoenix** [comment]
Absolute links:
[retinaface_mnet025_v1](http://insightface.ai/files/models/retinaface_mnet025_v1.zip)
[retinaface_mnet025_v2](http://insightface.ai/files/models/retinaface_mnet025_v2.zip)

And just in case original R50 model:
[retinaface_r50_v1](http://insightface.ai/files/models/retinaface_r50_v1.zip)

BTW, wouldn't you mind if I include part of your code in my [InsightFace-REST](https://github.com/SthPhoenix/InsightFace-REST) repo for MXNet->ONNX->TensorRT convertion?

**Comment by zheshipinyinMc** [comment]
I will try these models. just cite them.

**Comment by zheshipinyinMc** [comment]
i found a bug，
In mxnet symbol, BN has fix_gamma, if fix_gamma is true, then set gamma to 1 and its gradient to 0, you can find this in mxnet API.
for example, in retinaface_mnet025_v1, the output is different from 'conv_3_dw_batchnorm', because fix_gamma in 'conv_3_dw_batchnorm' is true，but its value is  0.000007107922556315316(you can see weight by Netron). So forward onnx model its('conv_3_dw_batchnorm') gamma is 0.000007107922556315316, but forward mxnet model, actually its'conv_3_dw_batchnorm' gamma is 1.

**Comment by SthPhoenix** [comment]
Thanks! I'll try to fix it.

**Comment by SthPhoenix** [comment]
Still can't find how to fix it. Should I work with resulting ONNX, or somehow change gamma weights in MXNet graph?

**Comment by zheshipinyinMc** [comment]
I‘ll try to fix this.

**Comment by zheshipinyinMc** [comment]
I have upload fixed bn gamma models. @SthPhoenix

**Comment by SthPhoenix** [comment]
Great work! Now both nets work as intended. 
But I still can't understand how you fixed it, some example code would be much appreciated!

**Comment by zheshipinyinMc** [comment]
read params file, and change the value of gamma to 1.
here, some key code, later i will upload a new repo about how to modify json and params.
`input_param = './retinaface_mnet025_v1/mnet10-0000.params'
net_param = mx.nd.load(input_param)
gamma = net_param['arg:'+ bn_name + '_gamma'].asnumpy()
if fix_gamma == True: 
        gamma *= 0
        gamma += 1
        net_param['arg:'+ bn_name + '_gamma'] = mx.nd.array(gamma)
mx.nd.save(save_params_path,new_param) 
`

**Comment by SthPhoenix** [comment]
Oh, I get it now,  thanks!

**Comment by SthPhoenix** [comment]
Here's my code to fix MXNet model before export:
```python
def mxnet_model_fix(input_symbol, input_params, write=True):
    names = []
    fix_gamma_layers = []

    with open(input_symbol, 'r') as _input_symbol:
        fixed_sym = json.load(_input_symbol)
        for e in fixed_sym['nodes']:
            if e['op'] == 'SoftmaxActivation':
                e['op'] = 'softmax'
                e['attrs'] = {"axis": "1"}
            # Fix for "Graph must be in single static assignment (SSA) form"
            if e['name'] in names:
                e['name'] = f"{e['name']}_1"
            names.append(e['name'])
            if e.get('attrs', {}).get('fix_gamma') == 'True' and e['name'].endswith('_gamma'):
                fix_gamma_layers.append(e['name'])
        _input_symbol.close()

    fixed_params = mxnet_fixgamma_params(input_params, layers=fix_gamma_layers)

    if write is True:
        mx.nd.save(input_params, fixed_params)
        with open(input_symbol, 'w') as sym_temp:
            json.dump(fixed_sym, sym_temp, indent=2)



def mxnet_fixgamma_params(input_param, layers):
    net_param = mx.nd.load(input_param)
    for layer in layers:
        name = f'arg:{layer}'
        gamma = net_param[name].asnumpy()
        gamma *= 0
        gamma += 1
        net_param[name] = mx.nd.array(gamma)
    return net_param

```

**Comment by zheshipinyinMc** [comment]
nice!

**Comment by Talgin** [comment]
Hi, thank you for shared codes and converted models, but mnet025_fix_gamma_v2.onnx model gives wrong landmarks and different head rectangle than gamma_v1 (I used the same code for postprocessing for gamma_v1 and gamma_v2). Please, check the resulting model, maybe I did something wrong.

**Comment by SthPhoenix** [comment]
v1 and v2 models are different, and gives different results even in MXNet, v2 seems to have worse accuracy in tests

**Comment by Talgin** [comment]
> tests

Oh sorry, I just tested the original mnet25_v2 in mxnet and the landmarks are also going haywire and head rectangle is different.

**Comment by Talgin** [comment]
Hi, I've tested the original mnet25_v1 and converted mnet025_fix_gamma_v1.onnx model, but they give different accuracy. Original model was able to find all faces on the photo, but converted model missed some people. P.S. pre and postprocessing is similar to original retinaface.py (except that we changed scales to calculate each axis to draw outputs on original image).

**Comment by SthPhoenix** [comment]
I haven't tested models provided by @zheshipinyinMc, I have converted models a bit different way.
Just in case, ensure that input image in both versions is resized to same dimensions, since in MXNet Retina can take any size of input, while in ONNX it require fixed size, same as during onnx creation.
Also ensure that in both cases images have right channel order, either BGR or RGB, not sure which one is used by Retina. I have once lost many time debugging when missed this.

**Comment by zheshipinyinMc** [comment]
onnx models in this repo, i have compared their ouput, onnx ouput is almost same with mxnet.
onnx test code: Retinaface/mxnet2onnx_demo.py/onnx_inferred_demo
mxnet test code: Retinaface/face_feature_demo.py
i just compared output，no preprocess and postprocess. @SthPhoenix@Talgin

**Comment by mohamadHN93** [comment]
> onnx models in this repo, i have compared their ouput, onnx ouput is almost same with mxnet.
> onnx test code: Retinaface/mxnet2onnx_demo.py/onnx_inferred_demo
> mxnet test code: Retinaface/face_feature_demo.py
> i just compared output，no preprocess and postprocess. @SthPhoenix @Talgin

Hi In the orginial version of retinaface the input shape is (3,112,112) but here is (3,640,640), can you provide the onnx version with (3,112,112) since the I got error when I run the onnx conversion
