### ISSUE TITLE
Have you tried to convert alignment algorithm?

### ISSUE THREAD

**Issue by jeonginseo** [zheshipinyinMc/arcface_retinaface_mxnet2onnx#5]
I tried to convert the coordinateReg of insightface as below:
https://github.com/deepinsight/insightface/tree/master/alignment/coordinateReg

I modified all the things you mentioned about retinaface and arcface.
After conversion, the generated model seems to be same as original model, but its result is not similar to original one, and the result never changes when the input image changed.

Do you have any idea for this?
i think the problems are caused by prelu,flatten, or batchnorm.

**Comment by SthPhoenix** [comment]
Symptoms looks like pretty the same as in #4 , and model symbol also has some batchnorm layers with fixed gamma.
You could try applying fixes from that issue.

**Comment by zheshipinyinMc** [comment]
solved?@jeonginseo@SthPhoenix

**Comment by SthPhoenix** [comment]
I haven't tested outputs of this exact model, but SubCenter ArcFace having same fixed gamma issue, works as intended after this fix.
https://github.com/SthPhoenix/InsightFace-REST/issues/5#issuecomment-712313964

**Comment by jeonginseo** [comment]
Sorry I was late.
Actually, I failed to convert to onnx successfully and converted the model by using your another repo on caffe.
I had to fix the BN gamma, by
net.params[key_caffe][0].data.flat=1
